<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1efde84a23cb1dd99158969e1ab29acf
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RAD_BOOTSTRAP_3\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RAD_BOOTSTRAP_3\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1efde84a23cb1dd99158969e1ab29acf::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1efde84a23cb1dd99158969e1ab29acf::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
